### ISSUE TITLE
[BUG] Tests fail due to receipt still open when tearing down tests

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#173]
**To Reproduce**
`py manage.py test --parallel`

**Expected behavior**
All to pass, but `test_download_receipt_valid_token` and `test_download_receipt_used_token` fail

```
PermissionError: [Errno 13] The process cannot access the file because it is being used by another process: 'MyFinances\\media\\receipts\\mock_image_HSgxDYA.jpg'    
```

**Desktop**
 - OS: Windows

This DOES NOT FAIL VIA GITHUB ACTIONS, so i'm not sure how bad this bug is. Not sure if app still runs correctly or if it's just the tests that fail. Should be able to debug tomorrow unless someone wants to take this on

**Comment by TreyWW** [comment]
Looking for a contributor to help debug and fix this ASAP. Preferably on windows - easier to debug. Thanks :)

**Comment by TreyWW** [comment]
Still haven't been able to solve this.

Error gets called from `tearDown` in `tests/handler.py` line 61 and the line 64 `cleanup_uploaded_files([receipt.image for receipt in Receipt.objects.all()])`

**Comment by wnm210** [comment]
Weird issue if it occurs only on windows... can't help tho :/

**Comment by Domejko** [comment]
Yes it is a bit weird, I did tackle this issue today on Windows and I manage to reduce number of errors to 1 but it's still not 100% reproducible (`--shuffle` and `--reverse` are still giving 2 errors) and  `test_download_receipt_valid_token` is still showing up constantly. Tests on Linux are passing with out this bug. 
From what I have noticed and checked app is working correctly and tests are passed the problem is only with cleaning after testing. Since it's a web app then all servers are Linux based so the issue shouldn't be a serious problem, but either way it's good to know what's exactly going on. I will try again tomorrow to find a solution.

**Comment by Domejko** [comment]
I have been working on this issue for a while and it's a really irregular one. Eventually I didn't manage to get rid of it 100% but at this point test may pass successfully 3-4 times in a row with out any errors and on 5th iteration it will drop the same error but this time only on `test_generate_download_link_valid_receipt` and */media/receipts* folder wont be cleaned but with next successful iteration folder will be cleaned.
This have been done by isolating `ReceiptDownloadEndpointsTest` to separate test file, inheriting not from `ViewTestCase` but from `TestCase` and using `tearDownClass` classmethod instead of `tearDown`.
Since we know that it's and issue with cleaning up and it's probably based on how Windows handle this processes plus now with successful test it will be cleaned up it could be placed in `try/except` block for `PermissionError` only. We could also give some feedback to the user that test files haven't been cleaned due to random permission error in windows and it will be cleaned with next successful iteration.
I did some refactoring in **handler.py** file and have added a additional test case for user mismatch in `ReceiptDownloadEndpointsTest`. I will do the PR for those any time soon.
As comes to the bug issue and solution let me know are you satisfied with it (at least for the moment) and if yes then what do you think about catching this random `PermissionError` in `try/except` block and giving feedback to the person performing tests (it might be also just a comment in the code or in Readme in Contribution section).

**Comment by TreyWW** [comment]
Hey @Domejko,
Amazing! Yeah catching the PermissionError and printing that to the user is also a great idea, i'm happy for that to be added!

Great debugging though, good job! Take your time on the PR, no rush. Much appreciated, thanks :)

**Comment by Domejko** [comment]
@TreyWW  I'm happy to hear that ! Tomorrow is should push PR with that and for additional test also. In the PR description in **Related PRs, Issues etc** section should I select that it Closes #173 ?

**Comment by TreyWW** [comment]
Hey,

Sorry I completely missed your message. It's fine to mention that 173 is delayed but not closes since it is already closed

**Comment by Domejko** [comment]
No problem. I figured that if you don't want me to mention it you will let me know at PR.
