### ISSUE TITLE
bug: We store HTMX content in HTML files

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#261]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

I used HTML auto-formatter in VSCode and it screwed up the HTMX totally 😦
Can we change HTMX file extension to htmx so that I can disable auto-formatting only for HTMX files, but preserve for HTML?

**Comment by introkun** [comment]
@TreyWW could you please assign it to me?

**Comment by TreyWW** [comment]
Are you sure .htmx file extensions exist? Remember it needs to also be supported by all IDEs to allow HTML formatting.
I feel like it doesnt exist, because HTMX is just HTML attributes, e.g. `<a hx-get="my page">` (the hx-get="my page" part). 

You can install a HTMX plugin to do highlighting, e.g. https://marketplace.visualstudio.com/items?itemName=otovo-oss.htmx-tags

**Comment by introkun** [comment]
I'd propose to use single quotes inside double quotes.
Example: `<a href="{% url 'receipts dashboard' %}">My Receipts</a>`
vs current
`<a href="{% url "receipts dashboard" %}">My Receipts</a>`
