### ISSUE TITLE
Invoice bar overlaping [bug] 

### ISSUE THREAD

**Issue by v-j-jpg** [TreyWW/MyFinances#282]
### What version of MyFinances are you currently using?

Main (development)

### What device type are you currently facing the issue on?

Mobile

### Describe the bug

For MD,SM and XS sized screens the invoice bar options are overlaping
![image](https://github.com/TreyWW/MyFinances/assets/58274307/987d9f77-1387-43bc-b272-901cd37d2832)

![image](https://github.com/TreyWW/MyFinances/assets/58274307/97a20227-9ab7-463c-8148-4532f6c87b93)

**Comment by TreyWW** [comment]
This issue is open for anyone to work on, comment to be assigned :)

**Comment by v-j-jpg** [comment]
I have already looked into this so I am able to work on this issue :) 
Can you add some specs on how it should be resolved, how would you prefer to look?

**Comment by TreyWW** [comment]
Uhm to be honest I have no idea, I'm a little rubbish on the frontend. 

Maybe on the 
`<div tabindex="-1" id="status_banner" class="print-ignore fixed top-0 left-0 z-50 grid grid-cols-3 w-full p-4 bg-base-100 shadow text-base-content">`
element you can check if small device i think tailwind is like sm: and md: and lg: and then just use a different method instead of grid. Something that'll make the other rows go under it? im not too sure

**Comment by v-j-jpg** [comment]
@TreyWW I was thinking something like this so it fits the smaller screen:
<img width="359" alt="image" src="https://github.com/TreyWW/MyFinances/assets/58274307/3f54d644-06d1-4c41-aeea-8e4aea0000d8">
<img width="491" alt="image" src="https://github.com/TreyWW/MyFinances/assets/58274307/80d82898-0078-4e00-83a3-d2648206ac5d">

Or would you prefer something like: 
<img width="372" alt="Screenshot 2024-04-03 at 16 24 18" src="https://github.com/TreyWW/MyFinances/assets/58274307/489e6354-12bf-4ba9-8859-43b75a52332f">

or 
<img width="357" alt="image" src="https://github.com/TreyWW/MyFinances/assets/58274307/f79b73be-e339-4be0-b2e5-bbffb3b5d723">

**Comment by TreyWW** [comment]
The first one is quite nice, as long as it goes back to normal on larger screens (by using sm and lg)
