### ISSUE TITLE
bug: Tailwind - Invoice preview looks HORRIBLE

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#351]
### What version of MyFinances are you currently using?

latest

### What device type are you currently facing the issue on?

Mobile, Desktop

### Describe the bug

(need to generate images and description)

**Comment by TreyWW** [comment]
For example this

**Comment by KartikChinda** [comment]
Hi @TreyWW, I would love to work on this issue. However, since I am entirely new to open source contributions, I wanted to know if I am correct at pointing out the issue for this, well, issue, which I think is that the margin and the padding among these fields is too high and you would want them to be huddled a bit more closely together? Please correct me if I am wrong or provide more details, thanks!
