### ISSUE TITLE
implementation: Save a default invoice logo for client

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#443]
### How big is this feature?

Small

### Describe the problem

It would be nice to have the ability to upload a logo, and have it auto-fill for future invoices of the same client rather than uploading each time.

### Describe a possible solution

![image](https://github.com/user-attachments/assets/68742132-f190-4909-b766-3513436319b4)

- Add an option to Customer Defaults
- Auto fill if no invoice logo has been selected on the frontend in the backend request.

**Comment by hussein-mamane** [comment]
Hello, I am taking it. Thanks

**Comment by hussein-mamane** [comment]
hey, I am working on it the only trouble is uploading image; I think I am missing something since image when I upload it is just 
Image<[object file]>, can I have some help one the form
![form](https://github.com/user-attachments/assets/febceb4f-a80d-4a8f-93a4-03a9715ee04b)
The image is always None, am I missing something in the form ?
