### ISSUE TITLE
bug: List index out of range when accessing "Manage Team" after inviting a new member.

### ISSUE THREAD

**Issue by AlejandroCR9** [TreyWW/MyFinances#461]
### What version of MyFinances are you currently using?

v0.4.6

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

There is an error when trying to manage a team after a new user accept an invitation. This error specifically occurs after a new member has been added to the team and their permissions have not been affected. The console logs indicate an `IndexError: list index out of range.`

### Steps

1. Create two users.
2. Create a team with one of them.
3. Invite the remaining user to the team.
4. Accept the invite.
5. Try to access into "Manage Team" option (/dashboard/teams/) with any of the users.

**Comment by TreyWW** [comment]
Hey @AlejandroCR9 welcome to the project, and thank you for the contribution. 

Are you on the 0.4.6 release or just using the main branch. If using the release could you upgrade just to the latest branch and see if that fixes it. 

If you are on the latest branch no problem, we can look into this further. Thanks!

**Comment by AlejandroCR9** [comment]
I was in the main branch and I was guided by this text so I thought I was in 0.4.6 release, my bad. 
![image](https://github.com/user-attachments/assets/c55ed0ab-c276-41f3-af15-cbdaafa22a13)
But why the main branch does not have the last code of the release?

**Comment by TreyWW** [comment]
Hey! The issue is that the main branch hasn't had a release in ages, which ideally shouldn't be the case. Realistically I should update the version every push, but since we're changing so fast I just don't. 

We don't have a way to get the most up to date hash of the files (git commit) from python at the moment, so I had to fall back to a hardcoded version. 

Apologies for the confusion, I'll create a sub-issue and change the docs in a few days when I'm back.

Thanks again for the contribution

**Comment by TreyWW** [comment]
created #463
